### ISSUE TITLE
Rocky Linux support

### ISSUE THREAD

**Issue by scott80211** [netcore-jsa/unimus-linux-installer#7]
I'm trying to install on Rocky Linux 8.5.  After I run the install.sh file, it immediately says "doesn't support your OS".  Since Rocky is a CentOS replacement, I would hope this might be added and was hoping it was something easy to implement soon as we're wanting to move forward with this but RHEL licensing for us is a problem

**Comment by tomaskir** [comment]
@vik-unimus can you please pick this up and add support for Rocky?

Docker images are available at: https://hub.docker.com/r/rockylinux/rockylinux/tags
We should add tests for both 8.4 and 8.5.

`/etc/rocky-release` has all we need in a proper format, we should be able to utilize existing CentOS/RHEL params file.
